# Generated by Django 2.2.12 on 2020-10-12 12:48

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_fields.fields.DefaultStaticImageField(upload_to='../media/profile_pictures/'),
        ),
    ]
